version: '3.8'

services:
  app:
    build: .
    container_name: app-container
    environment:
      POSTGRES_USERNAME: prod
      POSTGRES_PASSWORD: prod
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: prod
    ports:
      - "8000:8000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
